services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
     - /home/marlon/Inception_web:/var/www/html
    depends_on:
     - wordpress
    networks:
     - inception
    env_file:
     - .env
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
     - /home/marlon/Inception_web:/var/www/html
    depends_on:
     - mariadb
    networks:
     - inception
    env_file:
     - .env
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
     - /home/marlon/Inception_database:/var/lib/mysql
    networks:
     - inception
    env_file:
     - .env

networks:
  inception:
    name: inception