services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
     - ./web:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
     - ./web:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
networks:
  inception:

